# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SocialAlarmClock' do
use_frameworks!
pod 'Alamofire', '2.0.0-beta.2'
end

target 'SocialAlarmClockTests' do

end

target 'SocialAlarmClockUITests' do

end

       
